[package]
name = "tower-breaker"
# When releasing to crates.io:
# - Remove path dependencies
# - Update html_root_url.
# - Update doc url
#   - Cargo.toml
#   - README.md
# - Update CHANGELOG.md.
# - Create "v0.1.x" git tag.
version = "0.1.0"
authors = ["Tower Maintainers <team@tower-rs.com>"]
license = "MIT"
readme = "README.md"
repository = "https://github.com/tower-rs/tower"
homepage = "https://github.com/tower-rs/tower"
documentation = "https://docs.rs/tower-breaker/0.1.0"
description = """
Load-based circuit-breaking middlewares
"""
categories = ["asynchronous", "network-programming"]
edition = "2018"
publish = false

[dependencies]
futures = "0.1.26"
tokio-timer = "0.2.4"
tower-load = { version = "0.1.0", path = "../tower-load" }
tower-service = "0.2.0"
tower-util = "0.1.0"
